services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    container_name: frontend
    restart: unless-stopped
    volumes:
      - avatar-images:/usr/share/nginx/html/avatars

  auth-service:
    build:
      context: ./auth-service
    container_name: auth_service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET="your_jwt_secret_key_change_this_in_production"
      - USER_SERVICE_URL=http://user-service:3002
    depends_on:
      - user-service
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=file:./data/users_db.db
      - AUTH_SERVICE_URL=http://auth_service:3001
      - PORT=3002
    restart: unless-stopped
    volumes:
      - user-data:/app/data

  game-service:
    build:
      context: ./game-service
    container_name: game_service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./data/pong_database.db
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./game-service/game_file:/app/data

  avatar-service:
    build:
      context: ./avatar-service
    container_name: avatar_service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=file:./data/avatar_db.db
      - PORT=3003
    restart: unless-stopped
    volumes:
      - ./avatar-service/files:/app/data
      - avatar-images:/app/avatars

volumes:
  user-data:
  avatar-images:
