services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    container_name: frontend

  auth-service:
    build:
      context: ./auth-service
    container_name: auth_service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET="your_jwt_secret_key_change_this_in_production"
      - USER_SERVICE_URL=http://user-service:3002
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=file:./data/users_db.db
      - AUTH_SERVICE_URL=http://auth_service:3001
      - PORT=3002
    volumes:
      - user-data:/app/data

  game-service:
    build:
      context: ./game-service
    container_name: game_service
    ports:
      - "3000:3000"
    environment:
      # - DATABASE_URL=file:./data/users_db.db
      # - AUTH_SERVICE_URL=http://auth_services:3001
      - PORT=3000
    restart: unless-stopped
    # volumes:
    #   - user-data:/app/data

volumes:
  user-data:
