services:
  # Frontend Service (React + Vite + TS + Tailwind)
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - ft_network
  #   restart: unless-stopped

  # Service d'authentification (Fastify + SQLite)
  auth-service:
    build: ./auth-service
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
      - USER_SERVICE_URL=http://user-service:3000
    ports:
      - "3001:3000"
    volumes:
      - auth_data:/app/data
    networks:
      - ft_network
    restart: unless-stopped

  # Service de jeu (Fastify + SQLite)
  # game-service:
  #   build: ./game-service
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - "3003:3000"
  #   volumes:
  #     - game_data:/app/data
  #   networks:
  #     - ft_network
  #   restart: unless-stopped

  # Service utilisateur (Fastify + SQLite)
  user-service:
    build: ./user-service
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3000
      - DATABASE_URL=file:./users_db.db
    ports:
      - "3002:3000"
    volumes:
      - user_data:/app/data
    networks:
      - ft_network
    restart: unless-stopped

  # Service de chat (Fastify + SQLite)
  # chat-service:
  #   build: ./chat-service
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - "3004:3000"
  #   volumes:
  #     - chat_data:/app/data
  #   networks:
  #     - ft_network
  #   restart: unless-stopped

networks:
  ft_network:
    driver: bridge

volumes:
  auth_data:
  # game_data:
  user_data:
  # chat_data:
