services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - GAME_SERVICE_URL=http://game-service:3002
      - PROFILE_SERVICE_URL=http://profile-service:3003
      - CHAT_SERVICE_URL=http://chat-service:3004
    depends_on:
      - auth-service
      - game-service
      - profile-service
      - chat-service
    networks:
      - ft_network
    restart: unless-stopped

  # Frontend Service (React + Vite + TS + Tailwind)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - ft_network
    restart: unless-stopped

  # Service d'authentification (Fastify + SQLite)
  auth-service:
    build: ./auth-service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=sqlite:///app/data/auth.db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
    ports:
      - "3001:3001"
    volumes:
      - auth_data:/app/data
    depends_on:
      - redis
    networks:
      - ft_network
    restart: unless-stopped

  # Service de jeu (Fastify + SQLite)
  game-service:
    build: ./game-service
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=sqlite:///app/data/game.db
      - REDIS_URL=redis://redis:6379
    ports:
      - "3002:3002"
    volumes:
      - game_data:/app/data
    depends_on:
      - redis
    networks:
      - ft_network
    restart: unless-stopped

  # Service de profil (Fastify + SQLite)
  profile-service:
    build: ./profile-service
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=sqlite:///app/data/profile.db
    ports:
      - "3003:3003"
    volumes:
      - profile_data:/app/data
    networks:
      - ft_network
    restart: unless-stopped

  # Service de chat (Fastify + SQLite)
  chat-service:
    build: ./chat-service
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DATABASE_URL=sqlite:///app/data/chat.db
      - REDIS_URL=redis://redis:6379
    ports:
      - "3004:3004"
    volumes:
      - chat_data:/app/data
    depends_on:
      - redis
    networks:
      - ft_network
    restart: unless-stopped

  # Redis pour le cache et les WebSockets
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ft_network
    restart: unless-stopped

networks:
  ft_network:
    driver: bridge

volumes:
  auth_data:
  game_data:
  profile_data:
  chat_data:
  redis_data:
