secrets:
    nginx_crt:
        file: ./secrets/nginx.crt
    nginx_key:
        file: ./secrets/nginx.key

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8443:443"
        container_name: frontend_service
        restart: unless-stopped
        volumes:
            - avatar-images:/usr/share/nginx/html/avatars
        secrets:
            - nginx_crt
            - nginx_key

    auth-service:
        build:
            context: ./auth-service
        container_name: auth_service
        ports:
            - "3001:3001"
        env_file: ./.env
        environment:
            - PORT=3001
            - USER_SERVICE_URL=http://user-service:3002
        depends_on:
            - user-service
        restart: unless-stopped

    user-service:
        build:
            context: ./user-service
        container_name: user_service
        ports:
            - "3002:3002"
        env_file: ./.env
        environment:
            - DATABASE_URL=file:./data/users_db.db
            - AUTH_SERVICE_URL=http://auth-service:3001
            - PORT=3002
        restart: unless-stopped
        volumes:
            - ./user-service:/app/data

    game-service:
        build:
            context: ./game-service
        container_name: game_service
        ports:
            - "3000:3000"
        env_file: ./.env
        environment:
            - DATABASE_URL=file:./data/pong_database.db
            - PORT=3000
        restart: unless-stopped
        volumes:
            - ./game-service/game_file:/app/data

    avatar-service:
        build:
            context: ./avatar-service
        container_name: avatar_service
        ports:
            - "3003:3003"
        environment:
            - DATABASE_URL=file:./data/avatar_db.db
            - PORT=3003
        restart: unless-stopped
        volumes:
            - avatar-images:/app/avatars

    online-service:
        build:
            context: ./online-service
        container_name: online_service
        ports:
            - "3004:3004"
        environment:
            - PORT=3004
        restart: unless-stopped

volumes:
    user-data:
    avatar-images:
