export const FPS = 60;
export const GAME_SPEED = 1.4
export const HEIGHT = 60;
export const WIDTH = 80;
export const BASE_PLAYER_SPEED = 0.8 * GAME_SPEED;
export const BASE_BALL_SPEED = 0.5 * GAME_SPEED;
export const MAX_BOUNCE_ANGLE = Math.PI / 5;
export const TOP_MARGIN = 1;
export const SPAWN_MARGIN = 8;
export const KILL_MARGIN = 4;
export const BASE_MAX_SCORE = 10;
export const BASE_COLOR = '#00F9EC';
export const BASE_SECONDARY_COLOR = '#66FF99';
export const IA_DIFF_NAME = ["Impossible", "Hard", "Medium", "Easy", "Joke"];